spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 1998
    driver-class-name: org.postgresql.Driver

server:
  error.include-message : always
